### ISSUE TITLE
About setup.py

### ISSUE THREAD

**Issue by Hxx2048** [DetectionTeamUCAS/Cascade-RCNN_Tensorflow#7]
when i run "python ./tools/train.py", there is a error "no module named 'libs'". 
the error information is as follow:
![error](https://user-images.githubusercontent.com/37645026/61864801-adac7000-af04-11e9-960d-df461e13c419.PNG)

I think this error may be about  'setup.py',  anyone know how to do?

**Comment by yangxue0827** [comment]
cd tools
python train.py @Hxx2048

**Comment by Hxx2048** [comment]
Thanks! you suggestion works! but i meet another question.
 after "cd tools; python train.py", the model keep in 'restore model' fro a long time , i don't know why.
like this
<img width="296" alt="错误2" src="https://user-images.githubusercontent.com/37645026/61881164-bb73ec80-af28-11e9-9510-fe242a0c9f3c.PNG">
@yangxue0827

**Comment by Hxx2048** [comment]
ok, i find the solution.  my convert_data_to_tf_record.py has something wrong.
